version: "2"
services:
    api:
        build: python-api
        ports: 
            - "5000:5000"
        volumes: 
            - /proc:/proc
        network_mode: host
        depends_on:
            - docker_mongo
    frontend:
        build: web
        ports: 
            - "3000:3000"
        network_mode: host
    depends_on:
        - docker_mongo
    docker_mongo:
        image: mongo
        ports:
            - "27017:27017"
        expose: 
            - "27017"
        network_mode: host