version: "3.3"
services:
    flask:
        container_name: "flask"
        build: 
            context: python-api
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"
        volumes: 
            - /proc:/proc
        environment:
            MONGODB_URL: "sopes1_mongodb:27017"
            PORT: 5000
        depends_on:
            - sopes1_mongodb
        networks:
            - frontend
            - backend
    frontend:
        container_name: "sopes1_frontend"
        build: 
            context: web
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        depends_on:
            - sopes1_mongodb
    sopes1_mongodb:
        container_name: "sopes1_mongodb"
        image: mongo
        ports:
            - "27017-27019:27017-27019"
        networks:
            - backend

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge