version: "3.3"
services:
    api:
        build: python-api
        ports: 
            - "5000:5000"
        volumes: 
            - /proc:/proc
        depends_on:
            - docker_mongo
    frontend:
        container_name: "sopes1_frontend"
        build: web
        ports: 
            - "3000:3000"
        depends_on:
            - docker_mongo
    docker_mongo:
        container_name: "sopes1_mongo"
        image: mongo
        ports:
            - "27017-27019:27017-27019"